### ISSUE TITLE
Remove propTypes on stateless components

### ISSUE THREAD

**Issue by andersekdahl** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#1]
Hi!
Thanks for this plugin, just what I was looking for!

However, this plugin doesn't remove propTypes from stateless components. That is, it doesn't remove this:
```jsx
const MyComponent = (props) => (
  <div></div>
);

MyComponent.propTypes = {
  someProp: React.PropTypes.string
};
```
Isn't this something that should be considered? I think stripping the `propTypes` should be okey in this case:
1. The object that `propTypes` is assigned to is a function in the same module.
2. The said function contains JSX directly inside the function body.

This doesn't work if you're not using JSX, so I could see it also removing the `propTypes` if:
1. The said function takes a single argument called `props` or destructuring is used on that single argument and it destructures it to variable names which also exists in the `propTypes` object.

An even simpler way of detecting it would be to always strip the `propTypes` if the object it's assigned to is a function. It would be simpler to implement, but with the risk of false positives. Although I can't think of a use case where you use this plugin but you have `propTypes` that you don't want to remove.

**Comment by davidtheclark** [comment]
Any possibility this could share logic with react-docgen, which has an [isStatelessComponent](https://github.com/reactjs/react-docgen/blob/713e848b80bc7e93778c4c6666d1cfde4d8e6e29/src/utils/isStatelessComponent.js) function? cc/ @fkling

**Comment by oliviertassinari** [comment]
That would be a good feature :+1:. The hardest part is to have an good heuristic to detect stateless functionnal component.
This thread can help https://github.com/gaearon/babel-plugin-react-transform/issues/57.
This comment could be usefull:
> **fkling** commented 24 days ago
FWIW, this is how react-docgen detects stateless components: https://github.com/reactjs/react-docgen/blob/master/src/utils/isStatelessComponent.js

**Comment by fkling** [comment]
If someone has a good idea how to separate into its own module, that's fine by me. I think the biggest issue is that all the utility methods expect a `NodePath` (from recast) to be passed, in order to resolve things in scope. This seems to limit their usability for other tools.
Maybe we can generalize some of them though.
