### ISSUE TITLE
[question] Is is removing both - React.PropTypes and PropTypes?

### ISSUE THREAD

**Issue by Andarist** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#100]
Never had to write AST transforms, so its quite hard to deduce this from the source code.

Is it removing both versions of PropTypes? From what I understand its also working by default for whole `node_modules`. 

Another questions is - what exactly is stopping this transform to work? From my observations - PropTypes cannot use imported definitions, is that right?

Libraries I have problem with - [react-textarea-autosize](https://github.com/andreypopp/react-textarea-autosize), [react-visibility-sensor](https://github.com/joshwnj/react-visibility-sensor), [react-linkify](https://github.com/tasti/react-linkify/), [react-transition-group](https://github.com/reactjs/react-transition-group)

**Comment by oliviertassinari** [comment]
> Is it removing both versions of PropTypes?

What are the two versions?

> From what I understand its also working by default for whole node_modules.

It' working on your whole Babel setup. If you let babel traverse the `node_modules`, this plugin will too. Noticed that most people only let babel traverse their source code.

> what exactly is stopping this transform to work?

I don't understand, nothing is supposed to stop that transform to work.

**Comment by Andarist** [comment]
> What are the two versions?

I mean those imported from `prop-types` package and those imported from `react`.

> It' working on your whole Babel setup. If you let babel traverse the node_modules, this plugin will too. Noticed that most people only let babel traverse their source code.

Would be cool then if we can have `include` option here in this package to overwrite global setting.

**Comment by oliviertassinari** [comment]
> I mean those imported from prop-types package and those imported from react.

We don't touch that for now by default. You can try the `removeImport` option out. `react.` is a deprecated pattern, we don't handle it.

> Would be cool then if we can have include option here in this package to overwrite global setting.

I guess you are referring to the `include` option of babel-loader, not the same story here. You can ignore the `node_modules` with that option: https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types#ignorefilenames.

All of that should be in the README. If something isn't clear. Feel free to improve it 😄 .

**Comment by Andarist** [comment]
> We don't touch that for now by default. You can try the removeImport option out. react. is a deprecated pattern, we don't handle it.

Ok, hopefully libraries will catch up soon with the change. Ive already setup `removeImport` :)

> I guess you are referring to the include option of babel-loader, not the same story here. You can ignore the node_modules with that option: https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types#ignorefilenames.

I had in mind rather reversed scenario. I dont want to run any babel transformations on libraries code, except this one. So I would need something like `includeFilenames`

**Comment by oliviertassinari** [comment]
> I had in mind rather reversed scenario. I dont want to run any babel transformations on libraries code, except this one.

I don't see how an `includeFilenames` option would be of any help. Babel plugins are not supposed to choose which files to parses. It's supposed to be on userland.

**Comment by Andarist** [comment]
Ofc this should be applied in the userland, but there is no option for this
transform to run on specific files in opt-in manner. Only opt-out

**Comment by oliviertassinari** [comment]
@Andarist Well, we would accept a PR for that. But in order to work, you need to configure Babel to traverse that file.
