### ISSUE TITLE
[flow] The parameter passed to require() must be a literal string

### ISSUE THREAD

**Issue by steida** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#107]
With 0.4.4 version.

```js
if (state.opts.plugins) {
  const pluginsVisitors = state.opts.plugins.map((pluginName) => {
    const plugin = require(pluginName);
    return plugin({ template, types }).visitor;
  });

  programPath.traverse(visitors.merge(pluginsVisitors));
}
```

**Comment by oliviertassinari** [comment]
Is that an issue with flow parsing the source code of the project? I'm not sure how we could address it.

**Comment by steida** [comment]
Don't use dynamic require string I guess. I see, not sure how to solve it.

**Comment by oliviertassinari** [comment]
Regarding the why of this new lines of code, it can be summarized with that [tweet](https://twitter.com/olivtassinari/status/859171219484049409).

I have been adding that line to the `.flowconfig` file. The best option I could find.
```
[options]

module.ignore_non_literal_requires=true
```

**Comment by steida** [comment]
Thank you for the hint.

**Comment by oliviertassinari** [comment]
Also, you can tell flow to ignore the source of this package. I think that it's a better alternative to `ignore_non_literal_requires`.

**Comment by matthewmueller** [comment]
seems like there should be a way to either disable this line or make flow happy, dynamic requires are pretty common and ignore_non_literal_requires disables a useful feature for the 99% case.

**Comment by Andarist** [comment]
@oliviertassinari 

Im not that sure what exact purpose this dynamic require serves here. From what I see its needed somehow because of certain combination of babel plugins and their unsafe ordering. Will it be possible to get rid of it once babel7 gets released which will address issue of plugins ordering by adding an option to specify which plugin should run first and which plugin should run later?

**Comment by oliviertassinari** [comment]
> babel7 gets released which will address issue of plugins ordering by adding an option to specify which plugin should run first and which plugin should run later?

Yes, hopefully, we should be able to remove the plugins option and the associated code.

**Comment by sandersky** [comment]
Worst case if you want to solve it in this repo you can add `// $FlowFixMe` above the line in question.

**Comment by oliviertassinari** [comment]
I'm closing the issue. I haven't seen a report for a long time. I'm assuming Flow stopped linting the node_modules.
