### ISSUE TITLE
ReactNative: `Component` has no propTypes defined

### ISSUE THREAD

**Issue by joncursi** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#111]
I think I just ran into the [error situation mentioned here](https://www.npmjs.com/package/babel-plugin-transform-react-remove-prop-types#is-it-safe) while using this plugin in my React Native app.

I accidentally wrote this code in my `.babelrc`:

```
...
  "plugins": [
    ...
    "transform-react-remove-prop-types"
    ...
  ]
...
```

Note that I did NOT put it under the `production` environment. Now in development, a bunch of my imported RN components from node_modules are complaining about not having prop types defined:

![screen shot 2017-06-06 at 7 37 36 am](https://cloud.githubusercontent.com/assets/4974609/26827387/086f1582-4a8b-11e7-9729-69980b28de91.png)

I have tried resetting the yarn cache, uninstalling and re-installing node modules, all to no avail. Is there a solution to basically undo the work this package has done and restore my project to where it was to begin with? I don't understand why a refresh of `node_modules` isn't solving the problem.

Please see a cross-post I made on the RN repo for additional info: https://github.com/facebook/react-native/issues/14338

Thanks!

**Comment by oliviertassinari** [comment]
Is the FBLikeView coming from a node_modules? https://github.com/facebook/react-native-fbsdk/blob/master/js/FBLikeView.js.
[That section](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types#is-it-safe) of the documentation can example it. Try using the [`ignoreFilenames`](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types#ignorefilenames) option.

**Comment by joncursi** [comment]
Thanks for your reply @oliviertassinari !

I solved this with the worst solution possible: I gave up and shut down my computer for a few hours, rebooted later and the issue was gone. Hah. My guess is that removing `node_modules` and re-installing **was** enough, however react-native has some funky cache business going on with it's Watchman configuration and I may have been hitting those issues.

**Comment by oliviertassinari** [comment]
Maybe we should change the default value of `ignoreFilenames`. Thanks for letting me know that the issue if solved on your end. We will see if that issue come more often.
