### ISSUE TITLE
[question] /node_modules/prop-types/ functions expected in build?

### ISSUE THREAD

**Issue by timburgess** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#121]
We have a codebase based on [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate) v3.4. I've been looking at the `main.js` that gets built and it includes references such as `"./node_modules/prop-types/factoryWithThrowingShims.js"` and `var n=o("./node_modules/prop-types/node_modules/fbjs/lib/emptyFunction.js"),`. Am I right in thinking that prop-types are not being removed in the build?

The `.babelrc` used is:
```{
  "presets": [
    [
      "latest",
      {
        "es2015": {
          "modules": false
        }
      }
    ],
    "react",
    "stage-0"
  ],
  "env": {
    "production": {
      "only": [
        "app"
      ],
      "plugins": [
        "transform-react-remove-prop-types",
        "transform-react-inline-elements",
        "transform-react-constant-elements"
      ]
    },
    "analyze": {
      "only": [
        "app"
      ],
      "plugins": [
        "transform-react-remove-prop-types",
        "transform-react-inline-elements",
        "transform-react-constant-elements"
      ]
    },
    "test": {
      "plugins": [
        "transform-es2015-modules-commonjs",
        "dynamic-import-node"
      ]
    }
  }
}
```
and we most definitely pass the production flag with `cross-env NODE_ENV=production webpack ...` in our `package.json` scripts. All the code lives under the `/app` directory.

**Comment by oliviertassinari** [comment]
> it includes references such as "./node_modules/prop-types/factoryWithThrowingShims.js" and var n=o("./node_modules/prop-types/node_modules/fbjs/lib/emptyFunction.js"),

@timburgess This library responsaibility is to remove the PropTypes references between definitions and react components. We do not remove the imports. Dead code elimination tools manage it.
