### ISSUE TITLE
use babel-preset-env

### ISSUE THREAD

**Issue by hozefaj** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#126]
Probably a good idea to use [babel-preset-env](https://github.com/babel/babel/tree/master/experimental/babel-preset-env) instead of [yearly presets](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/blob/master/.babelrc#L2).

**Comment by oliviertassinari** [comment]
I agree.

**Comment by hozefaj** [comment]
Will send a pr with update.

**Comment by oliviertassinari** [comment]
@hozefaj Thanks, I will review it :).
