### ISSUE TITLE
@babel v7 Error: No substitution given for "NODE_ENV"

### ISSUE THREAD

**Issue by mike1808** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#130]
When I tried to use this plugin with @babel v7.0.0-beta.34 I got the following error:

```
ERROR in ./components/app/App/App.jsx
Module build failed: Error: No substitution given for "NODE_ENV"
    at /home/michael/workspace/tmbl-front/node_modules/@babel/template/lib/populate.js:16:15
    ...
    =============
    at PluginPass.Program (/home/michael/workspace/tmbl-front/node_modules/babel-plugin-transform-react-remove-prop-types/lib/index.js:78:25)
  ...
 @ ./app.jsx 9:0-43
 @ multi @babel/polyfill whatwg-fetch ./setup.prod.js ./app.jsx
```

**Comment by oliviertassinari** [comment]
@mike1808 Thanks for opening the issue. I haven't prioritized it as I find likely it's a regression on babel side. I'm hoping it will be fixed on their side. If you think otherwise, let me know :).

**Comment by mike1808** [comment]
@oliviertassinari I'm using babel v7 in production and everything works except your plugin. I don't it's a regression.

Here is repo where you can reproduce it.

https://github.com/mike1808/babel-prop-plugin-bug

**Comment by danez** [comment]
I opened it in babel https://github.com/babel/babel/issues/7035

**Comment by oliviertassinari** [comment]
@danez good call :).
