### ISSUE TITLE
Transform not being applied to node_modules

### ISSUE THREAD

**Issue by ryanheathers** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#138]
Hi, thanks for the great plugin. However I am having trouble getting it to behave as expected.

Per the docs, anything in `node_modules` is transformed by default unless/until it is specifically _excluded_: https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types#ignorefilenames.

However that doesn't appear to be the case for my setup. I have a folder in node_modules that is not getting transformed.

My webpack file applies the babel-loader against a specific node_modules folder. This setup is working great for my other babel plugins.
```
module: {
  rules: [
    {
      test: /\.(js|jsx)$/,
      include: [
        path.resolve(__dirname, 'src'),
        path.resolve(__dirname, 'node_modules/my-cool-framework')
      ],
      loaders: ['babel-loader']
    }
  ]
}
```

Here is my .babelrc:
```
{
    "plugins": [
      // enables react to work with HMR
      "react-hot-loader/babel",

      // es7 class properties
      "transform-class-properties",

      // object rest/spread support
      "transform-object-rest-spread",

      // styled-components pre-processing
      "styled-components"
    ],

    "presets": [
      //jsx to js
      "react",

      // es6, disable commonjs modules to allow tree shaking
      ["es2015", { "modules": false } ],

      "es2016",
      "es2017"
    ],

    "env": {
      "test": {
        // allow Jest to work with es6 imports
        "plugins": ["transform-es2015-modules-commonjs"]
      },

      "production": {
        "plugins": ["transform-react-remove-prop-types"]
      }
    }
}
```

From my testing, any React components placed in my `src` folder have the propTypes stripped as expected. This is good.

However any files in the the `node_modules/my-cool-framework` folder do not receive a transformation. I copied an identical file between the two directories and checked the output upon build to verify this.

It doesn't look like there is a configuration option in this plugin to _include_ a specified folder. There's only the option to exclude. If I should try a different setup, please let me know. Thanks!

**Comment by oliviertassinari** [comment]
> Per the docs, anything in node_modules is transformed by default unless/until it is specifically excluded:

No, it's the other way around. We won't match the node_modules even if Babel is configured to do so (not the default behavior).

**Comment by ryanheathers** [comment]
I'm confused what the `ignoreFilenames` option does then. [The docs](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types#ignorefilenames) give the example of excluding `node_modules`, yet you're saying that it is already excluded by default?

In case this option is doing the inverse of what I expect, I tried adding it but the following also doesn't work to apply the transformation against my subfolder in `node_modules`.
```
"production": {
  "plugins": [
    [ "transform-react-remove-prop-types", {
      "ignoreFilenames": ["node_modules"]
    }]
   ]
 }
```

Is there no way to transform a subfolder in `node_modules`?

**Comment by oliviertassinari** [comment]
My bad, we march everything by default: https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/blob/b5b2015a9b5fbe6fe92ef43c9f0283829f956d2e/src/index.js#L63-L66
But Babel don't traverse the node_modules by default.
I'm confused. I don't understand what you are trying to do. You configuration goes against your objective. 1. No change is needed here 2. You need to tell babel to take the node modules into account, not just webpack.

**Comment by ryanheathers** [comment]
Babel is transforming my folder in `node_modules`. The `include` block below takes care of that.

```
module: {
  rules: [
    {
      test: /\.(js|jsx)$/,
      include: [
        path.resolve(__dirname, 'src'),
        path.resolve(__dirname, 'node_modules/my-cool-framework')
      ],
      loaders: ['babel-loader']
    }
  ]
}
```
This configuration allows all my Babel plugins to work...except for yours, unfortunately. Any further thoughts you have on why would be great.

**Comment by oliviertassinari** [comment]
@ryanheathers Maybe it has nothing to do with the file location. Have you tried moving the code outside of the node_modules?

**Comment by ryanheathers** [comment]
Yep. If I copy an identical file from `node_modules` into my `src` dir, the file is transformed correctly. The same file in `node_modules` is ignored.
