### ISSUE TITLE
It seems it does not work when importing modules

### ISSUE THREAD

**Issue by romainneutron** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#14]
If I use this syntax, it works perfectly:

```js
import React from 'react';

export default class MyComp extends React.Component {
    render() { 
        //...
    }
}

MyComp.propTypes = {
    name: React.PropTypes.object
}
```

however, it does not work like this:

```js
import React, { Component } from 'react';

export default class MyComp extends Component {
    render() { 
        //...
    }
}

MyComp.propTypes = {
    name: React.PropTypes.object
}
```

**Comment by romainneutron** [comment]
For the record, I'm using React 15, and I've spotted the issue down to 
```js
              if (superClass.matchesPattern('React.Component') || superClass.matchesPattern('Component')) {
                path.remove();
              }
```

In `AssignmentExpression` : `superClass.matchesPattern('Component')` returns false because of the second line of the `matchesPattern` function that return false at line 2:

```js
if (!this.isMemberExpression()) return false;
```

Changing `superClass.matchesPattern('Component')` to `superClass.node.name === 'Component'` solves my issue but I guess it's a wrong fix :)

**Comment by oliviertassinari** [comment]
@romainneutron Thanks for this feedback.
Can you confirm that this pattern is working?
```js
import React, { Component } from 'react';

export default class MyComp extends Component {
    static propTypes = {
        name: React.PropTypes.object
    };

    render() { 
        //...
    }
}
```
That sounds like the right direction.
We should refactor the `AssignmentExpression` to use some part of the `ClassProperty ` logic.

**Comment by romainneutron** [comment]
I confirm @oliviertassinari , it works better using your snippet

**Comment by oliviertassinari** [comment]
@romainneutron I have just merged a fix.

**Comment by romainneutron** [comment]
Thanks for your fast response
