### ISSUE TITLE
.babelrc "env" ignore in babel v6

### ISSUE THREAD

**Issue by gknapp** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#149]
How can you run this plugin for production builds only? I can only seem to run it when it's in my root `plugins` section of `.babelrc`.

As far as I can tell, babel v6 has broken the documented `"env": {}` option and was only fixed in v7.

See: babel/babel#4539 and babel/babel#5276

**Comment by oliviertassinari** [comment]
@gknapp You can use the wrap option as a workaround. But I would encourage you to find a solution on Babel side. I'm 99% confident that the `"env": {}` option still work. It would have been such a major change.

**Comment by oliviertassinari** [comment]
@gknapp You can use the wrap option as a workaround. But I would encourage you to find a solution on Babel side. I'm 99.99% confident that the `"env": {}` option still work. It would have been such a major change.
