### ISSUE TITLE
No support for babel 7

### ISSUE THREAD

**Issue by taoweicn** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#156]
I used babel 7 with `.babelrc` and followed the README, but I found it's useless to write
```JSON
{
  "env": {
    "production": {
      "plugins": ["transform-react-remove-prop-types"]
    }
  }
}
```
in `.babelrc`.
However, when I only wrote ` "plugins": ["transform-react-remove-prop-types"]`, it works in any environment(development & production).

**Comment by oliviertassinari** [comment]
@taoweicn I don't understand, what's the point?

**Comment by taoweicn** [comment]
> @taoweicn I don't understand, what's the point?


The code below both are my `.babelrc` config.

When I wrote this, it will NOT work in babel7:
```json
{
  "env": {
    "production": {
      "plugins": ["transform-react-remove-prop-types"]
    }
  }
}
```

When I wrote this, it will work in both development and production environment:
```json
{
  "plugins": ["transform-react-remove-prop-types"]
}
```

**Comment by oliviertassinari** [comment]
@taoweicn If you don't set NODE_ENV=production or BABEL_ENV=production, it's not a surprise.

**Comment by karolisgrinkevicius-home24** [comment]
For me it works in the same way as @taoweicn has mentioned.
I'm using
```
├── @babel/core@7.2.2
├── babel-plugin-transform-react-remove-prop-types@0.4.24
└── react@16.6.3
```
and the following `.babelrc` configuration:
```json
{
  "presets": [
    [
      "@babel/env",
      {
        "targets": {
          "browsers": ["last 2 versions"]
        },
        "modules": false,
        "useBuiltIns": "entry"
      }
    ],
    "@babel/react",
    "@babel/flow"
  ],
  "ignore": ["node_modules", "dist"],
  "plugins": ["react-hot-loader/babel", "@babel/plugin-proposal-class-properties", "@babel/transform-classes"],
  "env": {
    "production": {
      "plugins": ["transform-react-remove-prop-types", "react-remove-properties"]
    },
    "development": {
      "plugins": ["flow-react-proptypes"]
    }
  }
}
```

I also set the environment variable `BABEL_ENV` to `production`.

**Comment by oliviertassinari** [comment]
I think that you fill find better luck on the Babel side. If you can provide a failing test case, it would help.
