### ISSUE TITLE
babel-react-optimize

### ISSUE THREAD

**Issue by thejameskyle** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#16]
After reading your medium post, I decided to actually write the babel preset that I've wanted for a little while.

A while back I wrote a transform for Facebook for transforming pure class components into plain functions: https://github.com/thejameskyle/babel-plugin-react-pure-components

I'm taking that and a few other ideas I have and putting them into the same kind of monorepo that we use for Babel projects: https://github.com/thejameskyle/babel-react-optimize

Since you are doing very similar checks for pure components, I thought we could abstract that logic into babel-helpers and share it between plugins.

Would you be interested in taking this code and putting it in a shared repo?

**Comment by oliviertassinari** [comment]
@thejameskyle Thanks for taking the time to read my post.

> I decided to actually write the babel preset that I've wanted for a little while.

Yeah, that's a very good idea. We need someone with your network to spread it 🎉.

> Would you be interested in taking this code and putting it in a shared repo?

Are you referring to the [isStatelessComponent.js](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/blob/master/src/isStatelessComponent.js) file? Yes, I am.

**Comment by thejameskyle** [comment]
Cool, want to make a PR? Or I could do this tomorrow morning

**Comment by oliviertassinari** [comment]
Let me know if you still need help. I'm closing this issue as it has been inactive for a long time.
