### ISSUE TITLE
0.4.16 bug: Cannot read property 'referencePaths' of undefined at VariableDeclarator, lib/index.js:292:56

### ISSUE THREAD

**Issue by lencioni** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#160]
I haven't had time to dig in yet, but noticed this when updating from 0.4.15 to 0.4.16 in a repo.

**Comment by adammiller** [comment]
Seeing the same with a line like this: `PropTypes.oneOf(["Icon", "Button"]).isRequired`. If i remove that line, the error goes away.

**Comment by lencioni** [comment]
I haven't been able to reproduce this in the test suite, so I think it might be an interaction of multiple babel plugins. I can put up a PR that avoids this, but I am not sure what the cause is yet.

**Comment by lencioni** [comment]
@adammiller In my local testing, #161 prevents this crash. Can you try this out locally for me?

**Comment by maturanomx** [comment]
Just when I modify my dependencies, new release with the fix! 😆 

Awesome work!. I will try this new version. Let you know any problem 👍

**Comment by lencioni** [comment]
I found another problem, with ArrayPattern. Getting a fix ready now.

**Comment by lencioni** [comment]
@maturanomx I published 0.4.18 with some more fixes. Please let me know if you run into any more issues!
