### ISSUE TITLE
Cannot read property 'type' of undefined at memberExpressionRootIdentifier 

### ISSUE THREAD

**Issue by oliviertassinari** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#169]
The issue was first reported by @av-dev in https://github.com/facebook/create-react-app/issues/5312.
It seems to be coming from #158. @lencioni Any idea?

### Reproduction

- https://codesandbox.io/s/zlm3m439wm
- `yarn && yarn run babel`

**Comment by lencioni** [comment]
On phone at the moment but maybe it is getting tripped up by the nested object with the computed properties that are also member expressions?
