### ISSUE TITLE
Let's merge projects

### ISSUE THREAD

**Issue by nkt** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#17]
Hi. As I see your fork is much popular, than original project. Maybe we can join forces to make this plugin better?

**Comment by oliviertassinari** [comment]
Hi, thank for reaching me. I have just added you as a collaborator to the project.
I like this idea, but I don't have a specific plan on how to make it better.

**Comment by nkt** [comment]
First of all we should decide which project would be "main" and softly remove another. Your package more popular on npm, so I guess I have to mark my package as deprecated and suggest yours.

**Comment by oliviertassinari** [comment]
As the two projects are now pretty stable. I don't think that they will change a lot in the future.
We could just keep both available. I can't ask you to deprecate it. That's a lot to ask but that would definitly increase the popularity of this one 🎉 .

*Side thought*
I see one advantage on deprecating one for the other. That will make the choice simpler for people who want to add it to their project.
I have always been asking myself if a monopoly is good or not in the OSS environment. E.g. [react-toolbox](https://github.com/react-toolbox/react-toolbox) encouraged us to greatly improve [Material-UI](https://github.com/react-toolbox/react-toolbox).

**Comment by oliviertassinari** [comment]
@nkt Any news? I'm clearing my opened issues, this one has been inactive for a long time.
