### ISSUE TITLE
react-portal remove prop-types

### ISSUE THREAD

**Issue by romanlex** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#170]
I'm use react-portal in my app and babel-plugin-transform-react-remove-prop-types
But in production build of library I see imports of PropTypes

This is builded es version on Portal from node_modules
![image](https://user-images.githubusercontent.com/3369304/47907883-282bf000-de9d-11e8-891c-938b06e82e82.png)

In my umd or es build I see not removed prop-types(

**Comment by oliviertassinari** [comment]
@romanlex By default, Babel doesn't travers de node_modules for efficiency concerns. You have different options:
- Use https://material-ui.com/utils/portal/.
- Ask react-portal to use the wrap option.
- Change your Babel configuration to travers the node modules.

**Comment by romanlex** [comment]
I removed exclude option in my babel config
My babel compile all imports from node_modules
