### ISSUE TITLE
Does not work on classes not inheriting directly from Component

### ISSUE THREAD

**Issue by ju1ius** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#2]
It would be nice if the plugin searched up the inheritance chain for the base Component class.

**Comment by oliviertassinari** [comment]
Do you have an example? (That would be a good start to have a falling unit test)

**Comment by ju1ius** [comment]
Sure !
This is my use case:
```js
import React, {Component, PropTypes} from 'react';
import {renderToString} from 'react-dom/server';
import shallowCompare from 'react-addons-shallow-compare';

class PureRenderComponent extends Component {
    shouldComponentUpdate (nextProps, nextState) {
        return shallowCompare(this, nextProps, nextState);
    }
}

class SomeComponent extends PureRenderComponent {
    static propTypes = {
        foo: PropTypes.string.isRequired
    };
    render () {
        return <div>{this.props.foo}</div>;
    }
}

const output = renderToString(<SomeComponent foo="Püüürrr!" />);
```

**Comment by oliviertassinari** [comment]
Out of curiousity, why aren't you using the `pure` HOC of https://github.com/acdlite/recompose?

**Comment by ju1ius** [comment]
It's just easier on the eye for me.
I prefer seeing it near the top of the file than to scroll down 200 lines to find an `export default pure(Component)`.
And I can't get decorators to work in Babel 6...

**Comment by oliviertassinari** [comment]
> And I can't get decorators to work in Babel 6...

You can use https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy.

Fix https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/commit/0eb05113accca09f6687db9169d5936c45b8c396
