### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by kikoanis** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#22]
Not sure if this is a bug or an issue on my side.

I have a pure react component that returns a lodash map over a list
```
return map(mapList, (index) => {
```

when I build and run in production mode, I get an exception. I did some investigation and I concluded this line is the source of the issue
[
  if (node.callee && node.callee.object.name === 'React' && node.callee.property.name === 'createElement')](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/blob/master/src/isStatelessComponent.js#L6)
you assume that the callee always has an object and property which in this specific case is not.

I can only fix this by not returning map directly but rather assign it to a variable and at the end return it

```
const mapper = map(mapList, (index) => {
...

return mapper

```
Now not sure if you still need to guard that the callee has an object and property before carrying on the rest of the test.  otherwise just return false.

```
if (node.callee && node.callee.object && node.callee.object.name === 'React' && node.callee.property.name === 'createElement'
```

**Comment by oliviertassinari** [comment]
@kikoanis Thanks for raising this point. That's definitely an issue on my side. I'm gonna fix 👍.

**Comment by oliviertassinari** [comment]
Fix with https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/commit/a8ed0f2a4bdcf818aaa55ef22a425df617a932a0.
