### ISSUE TITLE
Publish latest

### ISSUE THREAD

**Issue by Swaagie** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#24]
Could https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/commit/775ebeaf8c5e4776826385bf7d06d0521f4dddf5 be publish as `0.2.6` or `0.3.0`. Was running into the same issue when directly inheriting from `Component`. Would be nice to be able to remove propTypes.

**Comment by oliviertassinari** [comment]
@Swaagie I'm on it. Just wait 10 minutes, I have also fixed https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/issues/22.

**Comment by oliviertassinari** [comment]
https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/commit/a446738450a24fc47c23a4730cfde5cec67b388f

**Comment by Swaagie** [comment]
Thanks for the quick reply and action! Keep up the good work :)
