### ISSUE TITLE
Is the babel-core dependency needed?

### ISSUE THREAD

**Issue by insin** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#27]
Does this plugin need `babel-core` in its `dependencies`? It doesn't seem to depend on it at runtime.

Context for my question: I'm hoping to include this plugin in [a Babel presets module](https://github.com/insin/nwb-babel-presets) which manually deduplicates dependencies to make Babel 6 presets less painful for people still on npm2.

**Comment by oliviertassinari** [comment]
> Does this plugin need babel-core in its dependencies?

No, this plugin shouldn't have any dependencies.
Thanks for raising this point. I'm gonna fix it.

**Comment by oliviertassinari** [comment]
https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/commit/3335501c6531aaeee56ec2bb8c1fa2d31d0f862c

**Comment by insin** [comment]
Great, thank you!
