### ISSUE TITLE
Wrapping propTypes with an environment check instead of removing them

### ISSUE THREAD

**Issue by insin** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#35]
Would it be feasible to wrap `propType` definitions in a `if (process.env.NODE_ENV !== 'production')` check (extracting them out first if they're part of a `React.createClass()`) instead of removing them completely?

This plugin is great and solves the problem of removing my own redundant `propTypes` for production, but it would be cool if it could also be adopted by authors transpiling reusable components to publish to npm, so your dependencies' `propTypes` could be available in development and test as normal, but automatically removed for production via the usual dead-code elimination process.

Could that be made an option into this plugin? Remove vs. move/wrap?

**Comment by oliviertassinari** [comment]
> but it would be cool if its could also be adopted by authors transpiling reusable components to publish to npm

That sounds like an awesome idea!

**Comment by oliviertassinari** [comment]
I'm working on it, it shouldn't be too hard, I'm already doing it here https://github.com/oliviertassinari/babel-plugin-transform-dev-warning/blob/master/src/index.js#L23.

**Comment by oliviertassinari** [comment]
@insin I have done a first iteration for this feature. I still miss the stage-1 class static syntax.

**Comment by insin** [comment]
Amazing, thanks!

Looking forward to integrating this into my component building setup :+1:

**Comment by oliviertassinari** [comment]
@insin I'm gonna add it to Material-UI too 🎉 .
However, I haven't tested it yet on a real project.
I have two unsupported cases:
- The old `React.createClass` 
- The unnamed class. 
That should only be edges cases that we could support with more effort.
