### ISSUE TITLE
Strategy for stripping propTypes from external packages

### ISSUE THREAD

**Issue by avindra** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#38]
This is a question.

Say I have a `.babelrc` file like this:

```json
{
  "presets": ["react", "es2015", "stage-1"],
  "env" : {
    "development" : {
        "presets" : ["react-hmre"]
    },
    "production" : {
        "plugins" : ["transform-react-remove-prop-types"]
    }
  }
}
```

And I'm building my project with webpack, so my JS loader looks like this:

```js
            {
                test : /\.jsx?$/,
                exclude : /(?:node_modules)/,
                loaders : [ 'babel', 'eslint' ],
            },
```

As you can see `node_modules` are excluded, because running the transformer on npm code would be excessive / expensive. However, doing so means propType definitions from packages such as [react-datepicker](https://github.com/Hacker0x01/react-datepicker) and [react-autosuggest](https://github.com/moroshko/react-autosuggest) will remain in the final build.

So my question is, what would be the smartest strategy for removing propTypes from external packages in a setup like this?

Should we be convincing package authors to add this plugin to their builds with the `wrap` mode on?

----

P.S., I've tried just running the `babel` cli tool to strip propTypes from the compiled build, but that doesn't work (I guess, due to safeguards within your package to validate variables named `propTypes` are actually React related).

**Comment by oliviertassinari** [comment]
> Should we be convincing package authors to add this plugin to their builds with the wrap mode on?

I think that convincing package authors to use this plugin would be an efficient strategy.
Most of them are already publishing an `es5` version of their package using Babel.

For one moment, I was worried about how we would handle `es6` published version.
No much package authors are publishing one as we are speaking, I don't have any test running under those conditions, but I believe it's already supported. #fingercrossed 🎌 .

I have no clue regarding package authors using `TypeScript`. 

> I've tried just running the babel cli tool to strip propTypes from the compiled build

That's an interesting approach. We should support it, I have never tried it.

**Comment by oliviertassinari** [comment]
@avindra I have added a test with an already transpiled code. It's not working for all the cases.

**Comment by oliviertassinari** [comment]
I'm closing this issue. The `wrap` mode is used in production with Material-UI ([.babelrc](https://github.com/callemall/material-ui/blob/master/.babelrc#L22)). This approach is working for us so far. We might have some edge cases. But I'm confident, we can address them.
