### ISSUE TITLE
Why is React.createClass not supported anymore?

### ISSUE THREAD

**Issue by peterdotjs** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#53]
First all @oliviertassinari thank you for maintaining this package and repo! 

I wanted to ask about the previously supported `React.createClass`. Was there a specific reason for dropping this support from the previous fork? Was there a specific issue in supporting or did you simply want to concentrate support for es6 class style.

I searched but I couldn't find any more info on this.

My current use case is a codebase that uses `React.createClass` across. Without doing a codemod I wanted to see if there was an alternative to take advantage of fully removing `propTypes` in production.

Thanks!
Peter

**Comment by peterdotjs** [comment]
actually nvm - looking at the docs again it seems like it's referring to the wrap mode specifically.

**Comment by oliviertassinari** [comment]
I have added a reference to the *mode* I'm talking to. I hope that it will help others #a154466.
Thanks for raising it.
