### ISSUE TITLE
Strip propTypes from React.createClass

### ISSUE THREAD

**Issue by jbellsey** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#55]
I've built the code as a gist, which I'm using as a custom babel plugin in my own projects. I'd be happy to create a PR to incorporate this feature, if it's of interest. 

Do you have docs on how your tests are structured?

https://gist.github.com/jbellsey/0fef4c161ec324fce1015d0f4f47fe21

**Comment by oliviertassinari** [comment]
Hi, I'm not sure to understand the issue. Don't we already have this feature?

Our tests are quite high level. You can found the raw datas in the [test/fixtures] (https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/tree/master/test/fixtures) folder.

**Comment by jbellsey** [comment]
Your readme indicates:

> We do not support the old React.createClass syntax

If that's not true, then you might remove that notice and add something to the readme to indicate that both old (createClass) and new (class) syntaxes are supported.

And if you've already got it covered, great! Feel free to close.

**Comment by oliviertassinari** [comment]
Right, it's specific to the `wrap` option. I'm gonna improve the README.md.

**Comment by oliviertassinari** [comment]
@jbellsey Thanks for raising this point. Should be better now.
