### ISSUE TITLE
Shouldn't this be a eslint plugin ?

### ISSUE THREAD

**Issue by helmus** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#63]
Excuse me if I'm completely missing the point here, but, this seems like a bit of an after the fact solution. 
In one way you could almost says it promotes not cleaning up your code. 

If your declare a propType and then don't use it in your compoment, essentially it's an unused param, and it should be highlighted or removed from the code trough eslint.

**Comment by oliviertassinari** [comment]
> Excuse me if I'm completely missing the point here

I think you do miss it 😁 .
The point is to have an eslint rule enforcing the use of `propTypes`.
You want to do it as `propTypes` are defining a clear API of your isolated component.

The thing is this code is only useful in development. It doesn't worth anything in production.
And worth, it's costing you bandwidth, parsing and evaluation time.

I'm gonna refer to the readme:

> ### The problem solved
Remove unnecessary React propTypes from the production build. You can save **bandwidth** by removing them.

**Comment by helmus** [comment]
@oliviertassinari 

But in the example in the readme you show a compoment that does not use the foo propType ( meaning is essentially an unused prop ). 
My argument is that you shouldn't have written the foo propType in the first place ( or remove it ).

Is this a bad example then ?

```
const Baz = () => (
  <div />
);

Baz.propTypes = {
  foo: React.PropTypes.string
};
```

**Comment by oliviertassinari** [comment]
@helmus Oh right, it's not a great example!
