### ISSUE TITLE
Updating wording of "Remove unnecessary React propTypes"

### ISSUE THREAD

**Issue by helmus** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#64]
> Remove unnecessary React propTypes from the production build. You can save bandwidth by removing them.

I think it is ambiguous as to why exactly they are unnecessary. ( and also caused my initial confusion  )

I would propose this:

> Remove React propTypes from the production build, as they are unnecessary in production. You can save bandwidth by removing them.

**Comment by oliviertassinari** [comment]
Do you want to submit a PR? 👍 😄

**Comment by helmus** [comment]
https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/pull/65

**Comment by oliviertassinari** [comment]
Thanks
