### ISSUE TITLE
PropTypes not removed from 'createClass' in some situations

### ISSUE THREAD

**Issue by necolas** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#68]
Looks like propTypes aren't removed from a component created with `createClass` in some situations. I've only quickly looked into it, but these are examples of code that still contains propTypes (and throws errors in production because the `View` propTypes don't exist anymore):

```js
import View from 'View';

const ScrollView = React.createClass({
  propTypes: {
    children: View.propTypes.children
  }
});
```

and

```js
import View from 'View';

const ScrollView = React.createClass({
  propTypes: {
    ...View.propTypes,
    onScroll: PropTypes.func
  }
});
```

**Comment by oliviertassinari** [comment]
One workaround would be to explicitlty export the `View` propTypes.
But I don't think that I have enough information to dig into it. Sorry.

**Comment by necolas** [comment]
Yes there are workarounds. However, I would expect these propTypes to be removed. What other information do you need?

**Comment by oliviertassinari** [comment]
> What other information do you need?

I would need a reproduction test case.
The `propTypes` identification logic is right [here](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/blob/master/src/index.js#L122-L147).
I'm wondering what could mess it.
Could you have a look at the logic checks? That may help.

**Comment by oliviertassinari** [comment]
I'm closing this issue as missing a reproduction test case. If you can find one, please go ahead.
Any help to improve this plugin is welcomed 👍 . Thanks.

**Comment by necolas** [comment]
Sorry I haven't gotten around to it yet :/
Perhaps this is something that can be rolled into the react preset if you haven't the time?

**Comment by oliviertassinari** [comment]
> Perhaps this is something that can be rolled into the react preset if you haven't the time?

I'm not sure to understand. How is this linked to time? IMHO, it's a matter of information, I don't have enough to have leverage.
