### ISSUE TITLE
Example on how to use in webpack

### ISSUE THREAD

**Issue by mschipperheyn** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#71]
I'm assuming something like this:

```jsx
    var RemovePropTypesPlugin = require('babel-plugin-transform-react-remove-prop-types');

    plugins: [
         new RemovePropTypesPlugin(),
    ]
```

**Comment by oliviertassinari** [comment]
I don't get it. Is this a feature request or a question?
This plugin don't have any integration with Webpack. I can't see the win of the above approach.

**Comment by mschipperheyn** [comment]
Just trying to keep it in webpack

**Comment by oliviertassinari** [comment]
I don't think that having another dependency to webpack is a good idea. I would rather separate concerns. I'm closing this issue. But thanks for the idea.
