### ISSUE TITLE
This plugin should ignore code inside node_modules

### ISSUE THREAD

**Issue by yaycmyk** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#82]
For example, my own code may be safe to prune propTypes, but `react-router` isn't, because they do some checks involving them at runtime in production mode: https://github.com/ReactTraining/react-router/blob/389df9c0ba603b758de4a979a34ee10276f9a8d0/modules/Router.js#L135

**Comment by oliviertassinari** [comment]
@yaycmyk I didn't know react-router was affected too. I'm reopening #70.

By the way, cool to see someone from @Zocdoc. Kind of the Aboard reference at @doctolib.

**Comment by yaycmyk** [comment]
Awesome ^_^
