### ISSUE TITLE
support new prop-types package

### ISSUE THREAD

**Issue by kentcdodds** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#87]
[Today's announcement](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html) includes a deprecation of `React.PropTypes` and an introduction of a new package `prop-types`. I expect not a whole lot of code will need to be added to support this. I'm happy to do it with a little direction.

**Comment by kentcdodds** [comment]
After thinking about it... I think that all we'd need to do is remove any import/require statements for `prop-types` and the normal plugin will handle the rest. Is this correct?

**Comment by oliviertassinari** [comment]
@kentcdodds Hey thanks, I was about to open an issue on that regard. I ended up with https://github.com/developit/proptypes/pull/10. I'm expecting this plugin to be resilient to that API update. I still have to try it out.

**Comment by oliviertassinari** [comment]
Oups, targeting the wrong repo `import PropTypes from 'prop-types';`.

**Comment by oliviertassinari** [comment]
> I think that all we'd need to do is remove any import/require statements for prop-types

We have never supported that feature. I'm wondering if dead code eliminator like uglifyJS2 are able to handle it. I'm gonna open an issue.
