### ISSUE TITLE
Go one step deeper by removing the PropTypes import

### ISSUE THREAD

**Issue by oliviertassinari** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#89]
This plugin has been focusing on doing a single task so far: removing the `propTypes`.
However, we could be smarter. As raised by @kentcdodds, removing the prop types is one thing, we  also have the import to take care of:
```js
import PropTypes from 'prop-types';
```

I'm wondering if UglifyJS2 and other dead code eliminator tools are smart enough to take care of it, otherwise, we would have to implement it.

**Comment by kentcdodds** [comment]
Unfortunately [uglify](http://lisperator.net/uglifyjs/#demo) and [babili](https://babeljs.io/repl/#?babili=true&evaluate=true&lineWrap=false&presets=&targets=&browsers=&builtIns=false&experimental=true&loose=false&spec=false&playground=true&code=import%20PropTypes%20from%20'prop-types'%0A&stage=0) will both leave the require/import there (and rightly so, you never know what happens on the other side of that import).

**Comment by oliviertassinari** [comment]
One more thought on that issue, identifying and removing the import is easier than removing the used `PropTypes`. We don't want to end-up in a situation where we remove the `PropTypes` but not the usage. We would break users code.

**Comment by kentcdodds** [comment]
Huh, that's a good point. Maybe we could opt-into this?

**Comment by azizhk** [comment]
I've created a PR implementing this: https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/pull/97
Let me know your thoughts.
