### ISSUE TITLE
Class without name breaks

### ISSUE THREAD

**Issue by rufman** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#9]
I have a context decorator that looks like this 
```jsx
export function context(contextTypes, passedContext) {
  return (DecoratedComponent) => {
    return class extends React.Component {
        static propTypes = DecoratedComponent.propTypes;
        static childContextTypes = contextTypes;
        getChildContext() {
          if (typeof passedContext === 'function') {
            return passedContext.bind(this)();
          } else {
            return passedContext;
          }
        }
        render() {
          return (
            <DecoratedComponent {...this.props} />
          );
        }
    };
  };
}
```
When compiling for production I get the following error: 
`Module build failed: TypeError: /.../index.js: Cannot read property 'name' of null`
Seems to be related to #7 (#8). Any ideas on how to stop the removal of props when using a HOC?

**Comment by oliviertassinari** [comment]
You are not providing any name to this class. That doesn't look like a valid syntax.

**Comment by rufman** [comment]
Interesting. That code compiled without an issue before. Adding a name fixes the issue, Thanks!

**Comment by oliviertassinari** [comment]
Look like using a class without a className is a [valid syntax](https://tc39.github.io/ecma262/#sec-class-definitions-runtime-semantics-evaluation). I'm gonna fix it.
