### ISSUE TITLE
PropTypes aren't removed when extending via Object.assign()

### ISSUE THREAD

**Issue by virgofx** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#91]
When a component extends from parent and the properties are extended, they are not removed.

Sample Code:

```js
export default class ComponentB extends ComponentA {
    static propTypes = Object.assign({}, {
        stringKey: PropTypes.string.isRequired,
    }, ComponentA.propTypes)
}
```

**Comment by oliviertassinari** [comment]
Hey, this was done by design, you can have a look at #29 for more detail. Basically, replacing `ComponentA` by `Component` do it.

**Comment by virgofx** [comment]
@oliviertassinari Is there anyway the above code can work ... The problem appears to be not the object.assign() but the extending of another child component. Can the tree just be walked? The comment regarding preferring composition over inheritance may have been valid years ago; however, is not the direction of React or ES in general (especially as evident with the dropping of more composition like components with React 15.5)

**Comment by oliviertassinari** [comment]
> Can the tree just be walked?

We do walk the tree one level deep on the file, but we don't go any deeper. You can have a look at [that test](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/blob/master/test/fixtures/es-class-inheritance/actual.js) for a more detail view of what's supported.

> appears is not set in stone as much of the community prefers object oriented design

That's your vision, mine is different. I'm using [recompose](https://github.com/acdlite/recompose) extensively with many pure functions.

**Comment by virgofx** [comment]
I don't have an issue with different visions of how to use the framework. The issue is nesting more than once doesn't work. If the tree walked recursively wouldn't that still fix the issue while not impacting how PropTypes are used (e.g. Composition vs. inheritance). Having PropTypes removed should mean PropTypes removed regardless of how one is using them in their application. I'd prefer to not have to fork and would be open to submitting a PR which includes recursive support if necessary.

**Comment by oliviertassinari** [comment]
> Having PropTypes removed should mean PropTypes removed regardless of how one is using them in their application.

I agree, still, we have to make tradeoffs, I like the Pareto principle.

Could you share a more detail example of you use case? See If that can easily be implemented? 

> open to submitting a PR which includes recursive support if necessary.

We are definitely open to support more use cases 👍 .

**Comment by virgofx** [comment]
Here is an example use case. Think of complex logic that is required for rendering common components.

```js

export default class ComplexLogicComponent extends Component {
    static propTypes = {
        baseKey: PropTypes.string.isRequired,
    }

    // Complex logic functions
   doComplex() {} 
   getComplex() {}
   updateComplexData {}

   // No render() since it's designed to be extended
}

export default class ComponentUsingComplex extends ComplexLogicComponent {
    static propTypes = Object.assign({}, {
        extraRenderProp: PropTypes.string.isRequired,
    }, ComplexLogicComponent .propTypes)

    render() { 
        // Use complex processing shared
    }
}
```

I'll submit a PR which addresses this hopefully by this weekend ... should just be a quick fix in the `isReactClass()` to use a while loop instead of returning false. 

Thanks for being open @oliviertassinari

**Comment by oliviertassinari** [comment]
I'm not sure what's going on, I would expect your example to work following the unit test we have.

**Comment by virgofx** [comment]
Updated my sample above to exactly what's not working in my system ... the top part was using `PureComponent`

**Comment by oliviertassinari** [comment]
I have tried out your example, that's working as expected on my end. Here is the output:
```js
import React, { PureComponent } from 'react';
import PropTypes from 'prop-types';

class ComplexLogicComponent extends PureComponent {

    // Complex logic functions that depend on state
    doComplex() {}
    getComplex() {}
    updateComplexData() {}

    // No render() since it's designed to be extended
}

/**
 * Component that requires complex logic
 */
class ComponentUsingComplex extends ComplexLogicComponent {

    render() {
        // Use complex processing from parent to help render node
    }
}
```

Still feel free to submit a PR if you find anything not working as expected.
