### ISSUE TITLE
Handle `create-react-class` package

### ISSUE THREAD

**Issue by trueadm** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#92]
With 15.5+ we are advising people who used to use `React.createClass` to switch to using ES2015 classes or the `create-react-class` package on NPM. Looking through the source, it appears that only `React.createClass` instances are being handled (I may be wrong though):

https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/blob/master/src/index.js#L87

Would it be possible to check for `create-react-class` too? Thank you.

CC/ @gaearon

**Comment by gaearon** [comment]
(FWIW the recommended way to import it is via `createReactClass()` call so maybe you can just hardcode that name)

**Comment by oliviertassinari** [comment]
What about:
- Using the `createReactClass` heuristic name.
- Moving both `React.createClass` and `createReactClass` checks under a `legacy` option disabled by default.

**Comment by kentor** [comment]
why move it under an option and not just check all methods?

**Comment by oliviertassinari** [comment]
I have changed my plan. I'm simply releasing a `minor` dropping the support of `React.createClass`.
