### ISSUE TITLE
publish to npm?

### ISSUE THREAD

**Issue by kentor** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#96]
Looking forward to the added support for `createReactClass`: a8530e3177c06b14a136bf98afb6238e815a1883

**Comment by oliviertassinari** [comment]
Sure, I'm gonna publish.

**Comment by oliviertassinari** [comment]
Closed with https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/commit/a718dc70a682ea2376e2350063e95d577f669b25.
