### ISSUE TITLE
PropTypes not removed for ES Class Inheritance

### ISSUE THREAD

**Issue by virgofx** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#99]
**./components/Parent.jsx**
```jsx
import PropTypes from 'prop-types';
import React, { PureComponent } from 'react';

export default class Parent extends PureComponent {
    static propTypes = {
        parentProp: PropTypes.string.isRequired,
    }
}
```

**./components/Child.jsx**
```jsx
import PropTypes from 'prop-types';
import React, { PureComponent } from 'react';
import Parent from './Parent';

export default class Child extends Parent {
    static propTypes = {
        childProp: PropTypes.string.isRequired,
    }
}
```

**Comment by oliviertassinari** [comment]
Your issue is tricky as we don't want to implement any import resolution logic.

The only path going forward that sounds reasonable is to implement something close to what we do with the stateless functional components. I mean looking at the render method for React element. That's not something I will prioritize.

**Comment by oliviertassinari** [comment]
That's not an issue I will prioritize as I don't think that we should encourage this pattern.
But feel free to subit a PR to fix that issue. 
You also have a quick fix available: rename `Parent` to `Component`.

**Comment by virgofx** [comment]
@oliviertassinari 
1) Why would you not encourage this pattern? One file per module/component is best practice and considered a standard everywhere. 

2) Renaming won't help as that wouldn't work with multiple components all referencing different components.

**Comment by oliviertassinari** [comment]
By pattern, I'm referring to the component composition over the class inheritance

**Comment by virgofx** [comment]
@oliviertassinari Do you know of an easy way to get the AST of the imported class (Not the limited bindings that don't contain the name)?

```js
function isReactClass(superClass, scope) {
  if (!superClass.node) {
    return false;
  }

  let answer = false;

  if (isPathReactClass(superClass)) {
    answer = true;
  } else if (superClass.node.name) { // Check for inheritance
    const className = superClass.node.name;
    const binding = scope.getBinding(className);
    if (!binding) {
      answer = false;
    } else {
      superClass = binding.path.get('superClass');

      if (isPathReactClass(superClass)) {
        answer = true;
      }
      else {
         // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         // Loop over imported class AST tree here
         // Or probably even better, move this logic into else{} of the ClassProperty traversing.
         // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      }
    }
  }

  return answer;
}
```

**Comment by virgofx** [comment]
@oliviertassinari Any insight into how to get the full AST of the imported class?

**Comment by oliviertassinari** [comment]
>  Any insight into how to get the full AST of the imported class? 

Are you referring to an AST of another file?
Linking back to my https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/issues/99#issuecomment-296429487, I think that this path is a dead-end

**Comment by virgofx** [comment]
Yeah ... I was trying to see if the reference bindings contained enough information to walk the tree upwards (so not necessarilly import resolution, but import traversing) ... My initial AST exploration revealed that the reference superclass bindings didn't contain the full AST tree so it wouldn't be able to easily detect the node name/path.  That's where I was wondering if there was an *easy* way to get this -- without having to do any file stats/imports and reparses. (That would probably hurt performance and something not needed). 
  My only other thought would be to perform 2 passes (e.g. run the plugin and report any file path marked as *false* in an array that would be processed oncemore plucking from any file paths that were marked as true.  However, I believe babel performs plugin operations serially per file but in an async manner which means any repeat passes is only *per file* and not per entire set which would not allow any local state to store the entire first round pass results.  

Not sure if you have any other thoughts?

**Comment by oliviertassinari** [comment]
@virgofx The approach I was suggesting is to replicate the stateless functional pattern to the *classes*. I mean, we could be:
- Looking for the render method
- Looking for a potential element returned by that render method

**Comment by EnoahNetzach** [comment]
could supporting a comment annotation in the class declaration (and variable definition) solve this issue?

I mean something like:
```js
class Child extends Parent /* remove-proptypes */ {}

const Component /* remove-proptypes */ = connect()
```

**Comment by virgofx** [comment]
@EnoahNetzach Comment annotations would work, just not as elegant if it could be detected automatically. I think at least having alternate solutions is a good thing as it makes the plugin more robust. Still wish there is an easy way to walk the parent AST.
